// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQMQhk9NQbqXakWGjXW3ZiZJJJYs18Dhc',
    appId: '1:144944981882:web:39e2070362b7643c2058c3',
    messagingSenderId: '144944981882',
    projectId: 'proyecto-grupal-sig-a251c',
    authDomain: 'proyecto-grupal-sig-a251c.firebaseapp.com',
    storageBucket: 'proyecto-grupal-sig-a251c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM9CanvfDiQI9EsC-UqxK4_VhpOD6T8cY',
    appId: '1:144944981882:android:8005004e2038e3e62058c3',
    messagingSenderId: '144944981882',
    projectId: 'proyecto-grupal-sig-a251c',
    storageBucket: 'proyecto-grupal-sig-a251c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANDb8XcFA-RLRYI9PVhb1DqH4e_B8TR-E',
    appId: '1:144944981882:ios:45a898159903837b2058c3',
    messagingSenderId: '144944981882',
    projectId: 'proyecto-grupal-sig-a251c',
    storageBucket: 'proyecto-grupal-sig-a251c.appspot.com',
    iosBundleId: 'com.example.proyectoGrupalSig',
  );
}
